# This is an OpenEMPIRE configuration file used for test runs.
# To be used with the execution script run.py

use_temporary_directory: True                          # Specifies whether to use a temporary directory for operations
temporary_directory: './'                              # Path to the temporary directory used for certain operations
forecast_horizon_year: 2025                            # Target or end year for the run
number_of_scenarios: 1                                 # Number of scenarios in every investment period
length_of_regular_season: 24                           # Number of hours in a regular season
regular_seasons: ['winter', 'spring']
discount_rate: 0.05                                    # Rate used to discount future cash flows to present value
wacc: 0.05                                             # Weighted average cost of capital
optimization_solver: "Gurobi"                          # Mathematical solver used for optimization tasks
use_scenario_generation: True                          # Indicates if scenarios should be generated dynamically
use_fixed_sample: False                                # Specifies if fixed scenario samples should be used  
filter_make : False                                    #
filter_use : False                                     #
copula_clusters_make: False                            # Make copula clusters (for copula-strata SGR)
copula_clusters_use: False                             # Copula-based scenario generation (strata/filter approach)
copulas_to_use: ["electricload"]                       # Emprical copula construction of ["electricload", "hydroror", "hydroseasonal", "solar", "windoffshore", "windonshore"]
n_cluster : 10                                         #
moment_matching : False                                #
n_tree_compare : 20                                    # Number of trees to compare for moment matching and copula-sampling
emission_cap_flag: False                                # Indicates if there's a cap on CO2 emissions
compute_operational_duals: True                        # Resolve empire with fixed investment variables and write new duals
print_iamc_flag: True                             # Output should be printed in a IAMC-compatible format
write_in_lp_format: False                              # Problem should be written in Linear Programming format
serialize_instance: False                              # Serialize the data structure or model for later use
north_sea_flag: False                                       # Whether the north sea is modelled or not
leap_years_investment: 5                               # Number of years per period (default: 5)
time_format: "%d/%m/%Y %H:%M"                          # Time format for scenario data files
lopf_flag: False
lopf_method: "angle"
lopf_kwargs:
  couple_to_existing_flows: false
  # existing_flow_candidates: ["transmisionOperational"]
  reactance_param_name: "lineReactance"   # <— matches your .tab
  reactance_from_susceptance: false       # we’re providing reactance directly
  # OR if you only have susceptance:
  # reactance_from_susceptance: true
  # susceptance_param_name: "lineSusceptance"
benders_flag: False                     # Whether to use Benders decompsition 
max_benders_iterations: 50
include_hydro_node_limit_constraint_flag: False